#!/bin/bash

set -e -o pipefail

cat > ssh.config << EOF
Host *
    User vagrant
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
    PasswordAuthentication no
    IdentityFile $HOME/.vagrant.d/insecure_private_key
    IdentitiesOnly yes
    LogLevel FATAL
EOF
