- hosts: control
  sudo: true
#  gather_facts: false
  handlers:
    - name: restart zookeeper
      service: name=zookeeper-server state=restarted
  tasks:
    - name: add Cloudera signing key
      rpm_key: state=present key=http://archive.cloudera.com/cdh4/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera

    - name: install cdh4
      yum: state=present name=http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm
      
    - name: install zookeeper
      yum: state=present name=zookeeper-server

    - name: check to see if zookeeper init has been run
      stat: path=/var/lib/zookeeper/version-2
      register: zkinit_dir

    - name: generate zk data dirs
      command: service zookeeper-server init
      when: zkinit_dir.stat.isdir is not defined
      notify:
        - restart zookeeper

    - name: configure /var/lib/zookeeper/myid
      template: src=config/myid.j2 dest=/var/lib/zookeeper/myid
      notify:
        - restart zookeeper

    - name: configure /etc/zookeeper/conf/zoo.cfg
      template: src=config/zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
      notify:
        - restart zookeeper

    - name: enable zookeeper
      service: name=zookeeper-server enabled=yes
      notify:
        - restart zookeeper
