- hosts: executor
  sudo: true
#  gather_facts: false
  handlers:
    - name: restart mesos slave
      service: name=mesos-slave state=restarted 
  tasks:
    - name: configure /etc/mesos/zk
      template: src=config/zk.j2 dest=/etc/mesos/zk

    - name: configure /etc/mesos-slave/{ip, hostname}
      template: src=config/ip.j2 dest=/etc/mesos-slave/{{ item }}
      with_items:
        - ip
        - hostname

# only needed with docker
#    - name: additional mesos slave configuration
#      template: src=config/mesos_slave_{{ item }}.j2 dest=/etc/mesos-slave/{{ item }}
#      with_items:
#        - containerizers
#        - executor_registration_timeout
#      notify:
#        - restart mesos slave

    - name: enable mesos slave
      lineinfile: state=present dest=/etc/init/mesos-slave.conf regexp='^#start on' line='start on stopped rc RUNLEVEL=[2345]'
      notify:
        - restart mesos slave


#    - name: enable mesos slave
#      file: path=/etc/init/mesos-slave.override state=absent
#      notify:
#        - restart mesos slave

    - command: initctl reload-configuration
