# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

$num_control = 1
$num_executor = 1

$vb_memory = 1024
$vb_cpus = 2

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "chef/centos-7.0"
  #config.vm.provider :virtualbox
#  config.vm.provider :virtualbox do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in CoreOS, so tell Vagrant that so it can be smarter.
 #   v.check_guest_additions = false
  #  v.functional_vboxsf     = false
  #end

  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]

  (1..$num_control).each do |i|
    config.vm.define vm_name = "ctrl-%02d" % i do |config|
      config.vm.hostname = vm_name
      config.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.memory = $vb_memory
        vb.cpus = $vb_cpus
      end

      ip = "10.10.1.#{i+9}"
      config.vm.network :private_network, ip: ip, :netmask => "255.255.0.0"
    end
  end

  (1..$num_executor).each do |i|
    config.vm.define vm_name = "node-%02d" % i do |config|
      config.vm.hostname = vm_name
      config.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.memory = $vb_memory
        vb.cpus = $vb_cpus
      end

      ip = "10.10.2.#{i+9}"
      config.vm.network :private_network, ip: ip, :netmask => "255.255.0.0"
    end
  end
end
