---
- hosts: execute
  sudo: True
  tasks:
    - name: install docker keys
      apt_key: state=present url=https://get.docker.io/gpg
      #apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9

    - name: add docker repo
      apt_repository: state=present update_cache=yes repo='deb https://get.docker.com/ubuntu docker main'

    - name: install docker
      apt: state=present name=lxc-docker

