- name: ceph stuff
  hosts: storage
  sudo: true
  tasks:
    - name: create config file
      template: src=config/ceph.conf.j2 dest=/etc/ceph/ceph.conf

    - shell: ceph osd create {{ ceph_osd_id }}
      register: osd_create

    - name: create OSD dir
      file: state=directory path=/var/lib/ceph/osd/ceph-{{ osd_create.stdout }}

    - shell: ceph-osd -i {{ osd_create.stdout }} --mkfs --mkkey --osd-uuid {{ ceph_osd_id }}

# need one MON server (can also be ADMIN)
# need some OSD (object storage devices) servers
# MDS only needed for filesystem    
